### ISSUE TITLE
[Suggestion][1.16.4] Configurable Tools durability

### ISSUE THREAD

**Issue by drakray** [grim3212/AssortedTools#3]
Specifically the Multitools

Also, _maybe_ more multitools materials?, mainly for [CLib](https://www.curseforge.com/minecraft/mc-mods/clib)'s ingot (should cover most modded material type if using tags for recipe, great in conjunction with configurable durability)

**Comment by grim3212** [comment]
Yeah, I do plan on re-adding the configurability aspect to them I just haven't got around to it.
As for the more materials, the hard part for that is knowing what tools to use in the recipes.

**Comment by grim3212** [comment]
Closing this as the configurable tools and armor was added. [https://assortedmods.com/tools/matconfig](https://assortedmods.com/tools/matconfig). The second part would be a new request that I am still not entirely sure the best way to handle right now at least until tools are tagged themselves.

**Comment by grim3212** [comment]
I have come up with a way to get the second part working by just implementing the new materials in another mod as an optional dependency. The latest version supports [https://www.curseforge.com/minecraft/mc-mods/assorted-core](https://www.curseforge.com/minecraft/mc-mods/assorted-core) and adds in tools, armor, hammers, and multitools for each material as well as Emerald.

**Comment by drakray** [comment]
Seems to work perfectly :D
Could it be possible to up the maxUses though?, I like to have the multitools 6time the base durability, but Netherite and Platinum goes to 12000ish, and if I enter that, it revert to 10000 instead
Not really important, just a quirk of mine lol

Also, any plan to bring back the Ultimate Fist?, I LOVE OP stuff, especially to gently caress f#$%! Dragons (especially Ice&Fire's) XD

**Comment by grim3212** [comment]
Bumped the max for each of the config values up to 100,000 instead of 10,000. You should be good to go. As for Ultimate Fist, I am not sure. I kinda am trying to make the super OP stuff that GrimPack added more reasonable. If you have an idea of a way to balance it then I wouldn't mind bringing it back.

**Comment by drakray** [comment]
In 1.12, I used to make it more expensive to craft, and with way less durability, like 7.
Sure it could be enchanted with Mending, but I though it was nice to have around.
Maybe make another "add-on mod", specifically for this kind of OP stuff, without default recipe, this way map-maker would have to work for it, or people could just use it from creative.

Or it could just be dropped, like a relic of a bygone age XD

**Comment by grim3212** [comment]
I do like the sounds of some of those options. I think I still might try to keep it in Assorted Tools since the only other real OP item from GrimPack I can think of is doubleing with the Workbench Upgrades. But I'll need to think on it. Sounds like I should be able to figure something out and add it back in in some form.
